### ISSUE TITLE
Blacklist with an includes?

### ISSUE THREAD

**Issue by choubacha** [lintci/sidekiq-skylight#6]
I'm wondering if it might be nice to have the ability to blacklist by including a module into the job?

That was instead of looking at the blacklist we could just ask the class?

``` ruby

# Middleware code:
if worker.try(:blacklisted?)
  yield
else
  # ...
```

For the worker it might be something like:

``` ruby
class DummyWorker
  include Sidekiq::Worker
  include Sidekiq::Skylight::Blacklisted

  def perform
  end
end

module Sidekiq::Skylight::Blacklisted
  def blacklisted?
    true
  end
end
```

**Comment by blatyo** [comment]
Is there a scenario you had in mind where this style would be preferable? I'm open to changing the way blacklisting works, but this would be a backwards incompatible change. So, there would need to be a good reason to justify it.

Also, you're making the same mistake I've made before with `try`. `try` means return `nil` if `self` is `nil`, otherwise call the method passed. What you wanted to say was `if worker.respond_to?(:blacklisted?) && worker.blacklisted?`.

**Comment by choubacha** [comment]
The intention would be to minimize the cognitive distance between marking a worker as blacklisted and working on the worker. Most of the time, if I decide that something should not be profiled, I'll be working on that file. In which case, it's not only more convenient to annotate the worker in the file but it is also easier for the next engineer to work on that code to see that it is blacklisted from skylight. (Basically, it's easier because I don't need to open a separate file, or even remember that a blacklisting config exists somewhere)

As for `try`, it actually does do responds_to?:

http://www.rubydoc.info/docs/rails/Object%3Atry

``` ruby
def try(*a, &b)
  if a.empty? && block_given?
    yield self
  else
    public_send(*a, &b) if respond_to?(a.first)
  end
end
```

It does a public send if the implicit receiver responds to the first argument. What you are describing is the safe navigation operator that was just introduced into ruby 2.3.

**Comment by blatyo** [comment]
What you describe is appealing. However, the current setup works with ActiveJob where we don't have access to the job object the developer would write. How would you handle that situation?

Also, you're right about `try`. They [changed it](https://github.com/rails/rails/commit/99ea1a875b06feb4346869f371e2a57a2cc0a0fc) to behave the way you described in Rails 4. I've been using it since Rails 2 and didn't realize it changed.

**Comment by choubacha** [comment]
@blatyo Honestly, I wouldn't remove the current blacklist functionality (as that's the means to work with ActiveJob). I imagine it being an augmentation to the current means.

I don't think it's necessary, just that it's a simple enhancement that could improve legibility of my jobs :smile_cat:

**Comment by blatyo** [comment]
This gem is deprecated
